import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js";
import {CONFIG} from "./config.js?v=16";import {QualityManager} from "./QualityManager.js?v=16";import {World} from "./world/World.js?v=16";import {Player} from "./player/Player.js?v=16";import {Controls} from "./player/Controls.js?v=16";import {MobManager} from "./entities/Mob.js?v=16";import {Particles} from "./rendering/Particles.js?v=16";import {Lighting} from "./rendering/Lighting.js?v=16";import {Effects} from "./rendering/Effects.js?v=16";import {Weather} from "./rendering/Weather.js?v=16";import {AudioManager} from "./audio/AudioManager.js?v=16";import {Inventory,RECIPES,craft} from "./inventory/Inventory.js?v=16";import {HUD} from "./ui/HUD.js?v=16";import {Menu} from "./ui/Menu.js?v=16";import {SaveManager} from "./save/SaveManager.js?v=16";import {BLOCK,INFO,ITEM,ICON} from "./world/Block.js?v=16";import {SurvivalSystems} from "./systems/SurvivalSystems.js?v=16";import {NetworkManager} from "./network/NetworkManager.js?v=16";
class Game{
 constructor(){const save=SaveManager.load();if(save?.seed)CONFIG.WORLD.SEED=save.seed;this.quality=new QualityManager();CONFIG.QUALITY=this.quality.preset;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x87c9ef);this.camera=new THREE.PerspectiveCamera(CONFIG.RENDER.FOV,innerWidth/innerHeight,.05,CONFIG.RENDER.FAR);this.renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:this.quality.tier==="low"?"low-power":"high-performance"});this.quality.configureRenderer(this.renderer);if(this.quality.tier==="low")this.renderer.toneMapping=THREE.NoToneMapping;this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;document.getElementById("game").appendChild(this.renderer.domElement);
  this.controls=new Controls(this.camera,this.renderer.domElement);this.world=new World(this.scene,CONFIG);this.world.loadChanges(save?.changes||[]);this.player=new Player(this.camera,this.world,this.controls,CONFIG);this.inventory=new Inventory();this.player.setInventory(this.inventory);if(!save?.inventory){this.inventory.add(ITEM.SEEDS,8);this.inventory.add(ITEM.HOE,1);this.inventory.add(BLOCK.GRASS,32);this.inventory.add(BLOCK.DIRT,64);this.inventory.add(BLOCK.STONE,64);this.inventory.add(BLOCK.LOG,16);this.inventory.add(BLOCK.PLANKS,32);this.inventory.add(BLOCK.SAND,32);this.inventory.add(ITEM.APPLE,3)}
  this.hud=new HUD(this.player,this.inventory);this.mobs=new MobManager(this.scene,this.world,CONFIG.QUALITY);this.particles=new Particles(this.scene,CONFIG.QUALITY);this.light=null;this.weather=null;this.effects=new Effects(this.renderer);this.audio=new AudioManager();this.menu=new Menu(this);this.systems=new SurvivalSystems(this);this.network=new NetworkManager(this);this.THREE=THREE;this.vec=(x,y,z)=>new THREE.Vector3(x,y,z);this.running=false;this.inventoryOpen=false;this.mode="singleplayer";this.reducedMotion=false;this.installPrompt=null;this.lastFootstep=0;this.breakProgress=0;this.perfFrames=0;this.perfTime=0;this.perfCooldown=0;this.perfStable=0;this.dynamicPixelRatio=this.quality.preset.pixelRatio;this.outline=this.makeOutline();this.time=save?.time||180;this.last=performance.now();this.mobTimer=0;this.saveTimer=0;this.mineTimer=0;this.fallTimer=0;this.smokeTimer=0;const qv=document.getElementById("qualityValue"),qs=document.getElementById("qualitySelect");if(qv)qv.textContent=this.quality.tier.toUpperCase();if(qs)qs.value=this.quality.tier;this.setupInput();this.setupInventory();this.setupInstall();if(save?.inventory)this.inventory.deserialize(save.inventory);if(save?.systems)this.systems.deserialize(save.systems);if(save?.player)this.player.pos.set(save.player.x,save.player.y,save.player.z);addEventListener("resize",()=>this.resize());this.resize();this.setModeBadge();this.loop()}
 async start(){if(this.starting)return;this.starting=true;const boot=document.getElementById("bootSplash"),bar=document.getElementById("bootProgress"),status=document.getElementById("bootStatus");const setBoot=(pct,text)=>{if(bar)bar.style.width=pct+"%";if(status)status.textContent=text};try{await this.requestLandscape();this.mode="singleplayer";this.network.disconnect();this.setModeBadge();this.audio.start();this.menu.hideMain();this.running=false;setBoot(25,"Создаём стартовый участок…");this.world.cfg.WORLD.RENDER_DISTANCE=this.quality.preset.startupDistance;this.world.lastCenter="";const s=this.world.cfg.WORLD.CHUNK_SIZE,cx=Math.floor(this.player.pos.x/s),cz=Math.floor(this.player.pos.z/s);if(!this.world.chunks.has(this.world.key(cx,cz)))await this.world.generateChunk(cx,cz,false);setBoot(65,"Строим первый кадр…");this.world.processMeshQueue(20);await new Promise(requestAnimationFrame);this.world.processMeshQueue(20);const save=SaveManager.load();if(save?.player){this.player.health=save.player.health;this.player.hunger=save.player.hunger}else this.player.pos.y=this.findGround(this.player.pos.x,this.player.pos.z)+.02;this.world.cfg.WORLD.RENDER_DISTANCE=this.quality.preset.renderDistance;this.world.lastCenter="";
    // Heavy visual systems are optional: they must never prevent the world from starting.
    try{this.light=new Lighting(this.scene,this.world,CONFIG)}catch(e){console.warn("Lighting disabled",e);this.light=null}
    try{this.weather=new Weather(this.scene,CONFIG.QUALITY)}catch(e){console.warn("Weather disabled",e);this.weather=null}
    this.world.generateAround(this.player.pos.x,this.player.pos.z);setBoot(100,"Мир готов");this.running=true;this.renderer.domElement.requestPointerLock?.()}catch(err){console.error(err);this.menu.showMain();if(status)status.textContent="Не удалось загрузить мир"}finally{this.starting=false}}

 findGround(x,z){for(let y=CONFIG.WORLD.HEIGHT-1;y>=0;y--)if(INFO[this.world.getBlock(Math.floor(x),y,Math.floor(z))]?.solid)return y+1;return 70}
 newWorld(){this.network.disconnect();SaveManager.clear();location.reload()}
 hostLAN(){this.save();const u=`${location.protocol==="https:"?"wss":"ws"}://${location.host}/ws`;this.mode="lan-host";this.setModeBadge();this.menu.hideMain();this.network.connect(u,true);this.network.chatLine("★ Локальная игра открыта для друзей");this.network.syncHostWorld();this.running=true;this.renderer.domElement.requestPointerLock?.()}
 connectLAN(){const v=document.getElementById("lanAddress"),u=v?.value.trim();if(!u){this.network.chatLine("Укажи адрес LAN-сервера");return}this.mode="lan-client";this.setModeBadge();this.menu.hideMain();this.network.connect(u,false);this.running=true;this.renderer.domElement.requestPointerLock?.()}
 resume(){this.menu.hidePause();this.running=true;this.renderer.domElement.requestPointerLock?.()}
 save(){const ok=SaveManager.save({systems:this.systems.serialize(),seed:CONFIG.WORLD.SEED,time:this.time,player:{x:this.player.pos.x,y:this.player.pos.y,z:this.player.pos.z,health:this.player.health,hunger:this.player.hunger},inventory:this.inventory.serialize(),changes:this.world.serializeChanges()});if(ok){const t=document.getElementById("saveToast");t.textContent="✓ Мир сохранён";t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1200)}}
 toMenu(){this.save();this.network.disconnect();this.mode="singleplayer";this.setModeBadge();this.running=false;document.exitPointerLock?.();this.menu.hidePause();this.menu.showMain()}
 toggleInventory(){this.inventoryOpen=!this.inventoryOpen;document.getElementById("inventoryPanel").classList.toggle("hidden",!this.inventoryOpen);if(this.inventoryOpen){this.running=false;document.exitPointerLock?.();this.renderInventory()}else{this.running=true;this.renderer.domElement.requestPointerLock?.()}}
 setupInventory(){this.renderInventory();document.querySelectorAll("[data-recipe]").forEach((b,i)=>b.onclick=()=>{if(craft(this.inventory,RECIPES[i])){this.audio.block();this.renderInventory()}})}
 renderInventory(){const grid=document.getElementById("inventoryGrid"),recipes=document.getElementById("recipes");if(!grid||!recipes)return;grid.innerHTML="";const icon=id=>ICON[id]||"·";for(let i=0;i<36;i++){const s=this.inventory.slots[i],d=document.createElement("div");d.className="invSlot"+(i===this.inventory.selected?" selected":"");d.innerHTML=`${icon(s.id)}<small>${s.count||""}</small>`;d.onclick=()=>{this.inventory.selected=i<9?i:this.inventory.selected;this.renderInventory()};grid.appendChild(d)}recipes.innerHTML="";RECIPES.forEach((r,i)=>{const b=document.createElement("button");b.dataset.recipe=i;b.textContent=r.name;b.title=r.in.map(x=>`${INFO[x.id]?.name||"?"} ×${x.count}`).join(" + ");b.onclick=()=>{if(craft(this.inventory,r)){this.audio.block();this.renderInventory()}};recipes.appendChild(b)});document.getElementById("recipeStatus").textContent=`Выбрано: ${INFO[this.inventory.selectedItem()?.id]?.name||"Пусто"}`}
 setupInput(){document.getElementById("multiplayerButton")?.addEventListener("click",()=>document.getElementById("multiplayerPanel")?.classList.remove("hidden"));document.getElementById("closeMultiplayer")?.addEventListener("click",()=>document.getElementById("multiplayerPanel")?.classList.add("hidden"));document.getElementById("connectButton")?.addEventListener("click",()=>{const v=document.getElementById("serverAddress");let u=v?.value.trim();if(!u)u=`${location.protocol==="https:"?"wss":"ws"}://${location.host}/ws`;this.mode="multiplayer";this.setModeBadge();this.network.connect(u)});document.getElementById("disconnectButton")?.addEventListener("click",()=>this.network.disconnect());document.getElementById("chatSend")?.addEventListener("click",()=>{const i=document.getElementById("chatInput");this.network.chat(i.value);i.value=""});document.getElementById("chatInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"){this.network.chat(e.target.value);e.target.value=""}});addEventListener("keydown",e=>{if(e.code==="Escape"){if(this.inventoryOpen){this.toggleInventory();return}if(this.running){this.running=false;this.menu.showPause();document.exitPointerLock?.()}return}if(e.code==="KeyE")this.toggleInventory();if(e.code.startsWith("Digit")){const n=+e.code.slice(5)-1;if(n>=0&&n<9)this.inventory.selected=n}if(e.code==="KeyF"&&this.player.eat()){this.audio.block();this.particles.burst(this.player.pos.clone().add(new THREE.Vector3(0,1,0)),0xff5533,8)}});
  addEventListener("mousedown",e=>{if(!this.running)return;if(e.button===0)this.attackOrBreak();if(e.button===2)this.placeBlock()});addEventListener("contextmenu",e=>e.preventDefault());addEventListener("wheel",e=>{this.inventory.selected=(this.inventory.selected+(e.deltaY>0?1:-1)+9)%9});document.getElementById("jumpButton").onclick=()=>{this.controls.keys.Space=true;this.audio.jump()};document.getElementById("attackButton").onclick=()=>this.attackOrBreak();document.getElementById("useButton").onclick=()=>this.useSelected();document.getElementById("inventoryButton").onclick=()=>this.toggleInventory();document.getElementById("closeInventory").onclick=()=>{if(this.inventoryOpen)this.toggleInventory()};document.getElementById("closeContainer").onclick=()=>this.systems.close();document.getElementById("depositContainer").onclick=()=>this.systems.depositToChest();
  const joy=document.getElementById("joystick"),knob=document.getElementById("joystickKnob");let active=false;joy.addEventListener("pointerdown",e=>{active=true;joy.setPointerCapture(e.pointerId)});joy.addEventListener("pointermove",e=>{if(!active)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.min(40,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);knob.style.transform=`translate(${Math.cos(a)*l}px,${Math.sin(a)*l}px)`;this.controls.keys.KeyW=dy<-15;this.controls.keys.KeyS=dy>15;this.controls.keys.KeyA=dx<-15;this.controls.keys.KeyD=dx>15});const stop=()=>{active=false;knob.style.transform="";for(const k of ["KeyW","KeyA","KeyS","KeyD"])this.controls.keys[k]=false};joy.addEventListener("pointerup",stop);joy.addEventListener("pointercancel",stop);
  let lookId=null,lastX=0,lastY=0;this.renderer.domElement.addEventListener("touchstart",e=>{if(e.touches.length!==1)return;lookId=e.touches[0].identifier;lastX=e.touches[0].clientX;lastY=e.touches[0].clientY},{passive:true});this.renderer.domElement.addEventListener("touchmove",e=>{const t=[...e.touches].find(x=>x.identifier===lookId);if(!t)return;const dx=t.clientX-lastX,dy=t.clientY-lastY;lastX=t.clientX;lastY=t.clientY;this.controls.yaw-=dx*.006;this.controls.pitch-=dy*.006;this.controls.pitch=Math.max(-1.5,Math.min(1.5,this.controls.pitch))},{passive:true})}
 useSelected(){const s=this.inventory.selectedItem(),info=s?.id?INFO[s.id]:null;if(info?.food){if(this.player.eat())this.audio.block();return}if(s?.id===ITEM.HOE){const hit=this.player.raycast();if(hit&&[BLOCK.DIRT,BLOCK.GRASS].includes(hit.id)&&this.world.getBlock(hit.block.x,hit.block.y+1,hit.block.z)===BLOCK.AIR){this.world.setBlock(hit.block.x,hit.block.y,hit.block.z,BLOCK.FARMLAND);this.audio.block();this.particles.dust(new THREE.Vector3(hit.block.x+.5,hit.block.y+.5,hit.block.z+.5),0x7a4c2b,8);this.systems.award(2,"Первая грядка")}return}if(info?.place||info?.solid)this.placeBlock()}
 attackOrBreak(){const target=this.player.raycast();if(this.systems.interact(target))return;const result=this.mobs.attack(this.player);if(result.hit){this.audio.hit();this.effects.hit();if(result.dead){this.inventory.add(ITEM.RAW_MEAT,1);if(Math.random()<.25)this.inventory.add(ITEM.APPLE,1);this.systems.award(20,"Охотник на нежить");this.particles.burst(this.player.pos.clone().add(new THREE.Vector3(0,1,0)),0xb84b4b,20);}return}this.breakBlock()}
 breakBlock(){if(this.mineTimer>0)return;const hit=this.player.raycast();if(!hit||hit.id===BLOCK.BEDROCK)return;const info=INFO[hit.id];if(!info?.drop)return;const s=this.inventory.selectedItem(),tool=INFO[s?.id];if(info.tool&&(!tool?.tool||tool.tool!==info.tool||tool.power<(info.minPower||0)))return;const power=tool?.tool?(tool.power||1):1;this.mineTimer=Math.max(.08,info.hardness/power*.22);this.world.setBlock(hit.block.x,hit.block.y,hit.block.z,BLOCK.AIR);this.network.blockChanged(hit.block.x,hit.block.y,hit.block.z,BLOCK.AIR);this.systems.removed(hit.id,hit.block);this.inventory.add(info.drop,1);this.systems.award(2,hit.id===BLOCK.STONE?"Первый камень":"");this.particles.burst(new THREE.Vector3(hit.block.x+.5,hit.block.y+.5,hit.block.z+.5),hit.id===BLOCK.GRASS?0x58a63b:0xb0b0b0,12);this.audio.break();this.effects.hit();if(this.light)this.light.lastScan=""}
 placeBlock(){const hit=this.player.raycast();if(!hit?.previous)return;const p=hit.previous,s=this.inventory.selectedItem(),id=s?.id,info=INFO[id];if(!id||(!info?.solid&&!info?.place))return;let blockId=info.place||id;if(id===ITEM.SEEDS){if(this.world.getBlock(p.x,p.y-1,p.z)!==BLOCK.FARMLAND&&this.world.getBlock(p.x,p.y-1,p.z)!==BLOCK.DIRT)return;blockId=BLOCK.WHEAT}if(this.player.collides({x:p.x+.5,y:p.y,z:p.z+.5}))return;if(!this.inventory.remove(id,1))return;if(!this.world.setBlock(p.x,p.y,p.z,blockId)){this.inventory.add(id,1);return}this.network.blockChanged(p.x,p.y,p.z,blockId);this.audio.block();this.systems.placed(blockId,p);this.systems.award(1,blockId===BLOCK.CHEST?"Строитель":"");this.particles.burst(new THREE.Vector3(p.x+.5,p.y+.5,p.z+.5),0xffffff,5);if(this.light)this.light.lastScan=""}
 loop(){requestAnimationFrame(()=>this.loop());const now=performance.now(),dt=Math.min(.04,(now-this.last)/1000);this.last=now;this.perfFrames++;this.perfTime+=dt;if(this.perfTime>2){const fps=this.perfFrames/this.perfTime;this.perfFrames=0;this.perfTime=0;this.perfCooldown=Math.max(0,this.perfCooldown-2);if(fps<27&&this.perfCooldown<=0){this.perfCooldown=8;this.dynamicPixelRatio=Math.max(.62,this.dynamicPixelRatio-.08);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.dynamicPixelRatio));}else if(fps>52){this.perfStable+=2;if(this.perfStable>=12){this.perfStable=0;this.dynamicPixelRatio=Math.min(this.quality.preset.pixelRatio,this.dynamicPixelRatio+.04);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.dynamicPixelRatio));}}else this.perfStable=0}this.effects.update(dt);this.world.processMeshQueue(this.quality.tier==="low"?2.2:3.8);this.mineTimer=Math.max(0,this.mineTimer-dt);if(this.running&&!this.inventoryOpen){this.time+=dt;this.controls.updateCamera();this.player.move(dt);const shake=this.reducedMotion?0:this.effects.consumeShake();if(shake){this.camera.position.x+=(Math.random()-.5)*shake;this.camera.position.y+=(Math.random()-.5)*shake}this.mobTimer+=dt;this.saveTimer+=dt;const phase=(this.time%CONFIG.DAY.LENGTH)/CONFIG.DAY.LENGTH,night=phase<.25||phase>.75;if(this.mobTimer>3){this.mobTimer=0;if(night&&this.mobs.mobs.length<this.mobs.max&&Math.random()<.7){const a=Math.random()*Math.PI*2,r=16+Math.random()*22,x=this.player.pos.x+Math.cos(a)*r,z=this.player.pos.z+Math.sin(a)*r,y=this.findGround(x,z);this.mobs.spawn(x,y,z)}}const oldHealth=this.player.health;if(this.mobs.update(dt,this.player)&&this.player.health<oldHealth){this.effects.damage();this.audio.hurt()}if(this.player.health<=0)this.handleDeath();this.fallTimer+=dt;this.smokeTimer+=dt;this.worldStreamTimer+=dt;if(this.fallTimer>.65){this.fallTimer=0;this.world.tickFalling(this.player)}if(this.smokeTimer>.18){this.smokeTimer=0;this.emitCampfireSmoke()}this.particles.update(dt);this.systems.tick(dt);if(this.light)this.light.update(this.time/CONFIG.DAY.LENGTH*Math.PI*2,this.player,dt);this.network.tick(dt);this.network.update(dt);if(this.weather)this.weather.update(dt,this.player,this.time);const target=this.player.raycast();if(target){this.outline.visible=true;this.outline.position.set(target.block.x+.5,target.block.y+.5,target.block.z+.5)}else this.outline.visible=false;if(this.saveTimer>20){this.saveTimer=0;this.save();if(this.network.hosting)this.network.syncHostWorld()}if(this.worldStreamTimer>(this.quality.tier==="low"?1.0:.65)){this.worldStreamTimer=0;this.world.generateAround(this.player.pos.x,this.player.pos.z)} }this.hud.update(this.player.raycast(),this.time);this.renderer.render(this.scene,this.camera)}
 handleDeath(){this.particles.burst(this.player.pos.clone().add(new THREE.Vector3(0,1,0)),0xffffff,35);this.player.health=CONFIG.PLAYER.HEALTH;this.player.hunger=CONFIG.PLAYER.HUNGER;this.player.pos.set(0,this.findGround(0,0)+.02,0);this.mobs.mobs.forEach(m=>m.alive=false);this.save()}
 makeOutline(){const g=new THREE.BoxGeometry(1.01,1.01,1.01),m=new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:.8,depthTest:false});const o=new THREE.Mesh(g,m);o.visible=false;o.renderOrder=50;this.scene.add(o);return o}
 emitCampfireSmoke(){const p=this.player.pos;for(const [k] of this.systems.furnaces){const [x,y,z]=k.split(",").map(Number);if(Math.hypot(x-p.x,z-p.z)<18&&this.world.getBlock(x,y,z)===BLOCK.CAMPFIRE)this.particles.smoke(new THREE.Vector3(x+.5,y+1,z+.5),2)}}
 setupInstall(){window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();this.installPrompt=e;const b=document.getElementById("installButton");if(b)b.textContent="⬇ УСТАНОВИТЬ ПРИЛОЖЕНИЕ"});window.addEventListener("appinstalled",()=>{this.installPrompt=null;const b=document.getElementById("installButton");if(b)b.textContent="✓ ПРИЛОЖЕНИЕ УСТАНОВЛЕНО"});document.addEventListener("fullscreenchange",()=>{const active=!!document.fullscreenElement;for(const id of ["fullscreenButton","fullscreenPauseButton"]){const b=document.getElementById(id);if(b)b.textContent=active?"⛶ ВЫЙТИ ИЗ ПОЛНОГО ЭКРАНА":"⛶ ПОЛНЫЙ ЭКРАН"}})}
 showInstall(){const panel=document.getElementById("installPanel"),text=document.getElementById("installText"),btn=document.getElementById("nativeInstallButton");panel?.classList.remove("hidden");const standalone=window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone;if(standalone){text.textContent="Игра уже запущена как приложение. Можно включить полный экран из меню паузы.";if(btn)btn.classList.add("hidden");return}if(this.installPrompt){if(btn){btn.textContent="УСТАНОВИТЬ ПРИЛОЖЕНИЕ";btn.classList.remove("hidden")}}else{if(btn)btn.classList.add("hidden");const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);text.textContent=ios?"На iPhone/iPad: нажми «Поделиться» в Safari → «На экран Домой» → «Добавить». После этого игра откроется как отдельное приложение без адресной строки.":"Если браузер поддерживает установку, появится системная кнопка установки. Иначе открой меню браузера и выбери «Установить приложение» или «Добавить на главный экран»."}}
 async installApp(){if(this.installPrompt){this.installPrompt.prompt();const result=await this.installPrompt.userChoice;if(result.outcome!=="accepted")this.showInstall();this.installPrompt=null;return}this.showInstall()}
 async requestLandscape(){try{if(screen.orientation?.lock)await screen.orientation.lock("landscape");}catch(e){} }
async toggleFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return}const el=document.documentElement;if(el.requestFullscreen)await el.requestFullscreen({navigationUI:"hide"});else{const ios=window.navigator.standalone||/iphone|ipad|ipod/i.test(navigator.userAgent);if(ios){const t=document.getElementById("saveToast");t.textContent="Для полноэкранного режима добавь игру на экран Домой";t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}}}catch(e){}}
 setModeBadge(){const e=document.getElementById("modeBadge");if(e){e.textContent=this.mode==="multiplayer"?"ONLINE":this.mode.startsWith("lan-")?"LAN CO-OP":"SINGLEPLAYER";e.className=this.mode==="multiplayer"?"online":this.mode.startsWith("lan-")?"lan":"offline"}}
 setQuality(tier,persist=true){this.quality.choose(tier,persist);CONFIG.QUALITY=this.quality.preset;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.quality.preset.pixelRatio));this.renderer.toneMapping=this.quality.tier==="low"?THREE.NoToneMapping:THREE.ACESFilmicToneMapping;this.renderer.shadowMap.enabled=this.quality.preset.shadows;if(this.light)this.light.maxLights=this.quality.preset.maxLights;this.particles.maxItems=this.quality.preset.particles;this.world.cfg.WORLD.RENDER_DISTANCE=this.quality.preset.renderDistance;this.world.lastCenter="";const v=document.getElementById("qualityValue");if(v)v.textContent=this.quality.tier.toUpperCase()}

 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)}
}
const game=new Game();
const boot=document.getElementById("bootSplash"),bar=document.getElementById("bootProgress"),status=document.getElementById("bootStatus");
requestAnimationFrame(()=>{if(bar)bar.style.width="100%";if(status)status.textContent="Готово";setTimeout(()=>boot?.classList.add("done"),80)});
addEventListener("beforeunload",()=>game.save());
