import {BLOCK,ITEM,INFO,ICON} from "../world/Block.js?v=21";
const key=(p)=>`${p.x|0},${p.y|0},${p.z|0}`;
export class SurvivalSystems{
 constructor(game){this.game=game;this.chests=new Map();this.furnaces=new Map();this.crops=new Map();this.xp=0;this.level=1;this.achievements=new Set();this.lastWorldTick=0}
 award(xp=0,achievement=""){this.xp+=xp;while(this.xp>=this.level*100){this.xp-=this.level*100;this.level++;this.toast(`Уровень ${this.level}!`);this.game.particles?.burst(this.game.player.pos.clone().add({x:0,y:1,z:0}),0xffd34d,18)}if(achievement&&!this.achievements.has(achievement)){this.achievements.add(achievement);this.toast(`🏆 ${achievement}`)}}
 toast(t){const el=document.getElementById("saveToast");if(!el)return;el.textContent=t;el.classList.add("show");clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove("show"),1800)}
 placed(id,p){const k=key(p);if(id===BLOCK.CHEST&&!this.chests.has(k))this.chests.set(k,Array.from({length:18},()=>({id:0,count:0})));if(id===BLOCK.FURNACE&&!this.furnaces.has(k))this.furnaces.set(k,{input:0,progress:0,output:0});if(id===BLOCK.WHEAT)this.crops.set(k,{age:0,grow:0})}
 removed(id,p){const k=key(p);if(id===BLOCK.CHEST)this.chests.delete(k);if(id===BLOCK.FURNACE)this.furnaces.delete(k);if(id===BLOCK.WHEAT)this.crops.delete(k)}
 tick(dt){this.lastWorldTick+=dt;if(this.lastWorldTick<1)return;this.lastWorldTick=0;for(const [k,c] of this.crops){const [x,y,z]=k.split(',').map(Number),light=this.game.world.getBlock(x,y+1,z);c.grow+=INFO[light]?.emissive?1.8:.65;if(c.grow>=12){c.grow=0;c.age=Math.min(3,c.age+1)}}for(const f of this.furnaces.values()){if(!f.input)continue;f.progress+=1;if(f.progress>=5){f.progress=0;f.output=Math.min(64,f.output+1);f.input=0;this.award(4,"Первый слиток")}}}
 interact(hit){if(!hit)return false;const id=hit.id,p=hit.block;if(id===BLOCK.CHEST){this.openChest(key(p));return true}if(id===BLOCK.FURNACE){this.openFurnace(key(p));return true}if(id===BLOCK.WHEAT){const c=this.crops.get(key(p));if(c?.age>=3){this.game.world.setBlock(p.x,p.y,p.z,BLOCK.AIR);this.crops.delete(key(p));this.game.inventory.add(ITEM.WHEAT,1+Math.floor(Math.random()*2));if(Math.random()<.65)this.game.inventory.add(ITEM.SEEDS,1);this.award(8,"Первый урожай");this.game.particles.burst(this.game.vec(p.x+.5,p.y+.5,p.z+.5),0xe5c24d,10);return true}}return false}
 openChest(k){const panel=document.getElementById("containerPanel");panel.classList.remove("hidden");panel.dataset.kind="chest";panel.dataset.key=k;document.getElementById("containerTitle").textContent="СУНДУК";this.renderContainer(this.chests.get(k)||[])}
 openFurnace(k){const panel=document.getElementById("containerPanel");panel.classList.remove("hidden");panel.dataset.kind="furnace";panel.dataset.key=k;document.getElementById("containerTitle").textContent="ПЕЧЬ";this.renderFurnace(this.furnaces.get(k)||{input:0,progress:0,output:0})}
 close(){document.getElementById("containerPanel")?.classList.add("hidden")}
 renderContainer(slots){const el=document.getElementById("containerGrid");el.innerHTML="";slots.forEach((s)=>{const b=document.createElement("button");b.className="containerSlot";b.innerHTML=`${ICON[s.id]||"·"}<small>${s.count||""}</small>`;b.onclick=()=>{if(s.id){this.game.inventory.add(s.id,s.count);s.id=0;s.count=0;this.renderContainer(slots)}};el.appendChild(b)})}
 depositToChest(){const panel=document.getElementById("containerPanel"),ch=this.chests.get(panel.dataset.key),s=this.game.inventory.selectedItem();if(!ch||!s?.id)return;let slot=ch.find(x=>x.id===s.id&&x.count<64)||ch.find(x=>!x.id);if(!slot)return;if(!this.game.inventory.remove(s.id,1))return;slot.id=s.id;slot.count=(slot.count||0)+1;this.renderContainer(ch)}
 renderFurnace(f){const el=document.getElementById("containerGrid");el.innerHTML=`<div class="furnaceInfo">Вход: ${ICON[f.input]||"·"} ${f.input?INFO[f.input]?.name:"пусто"}<br>Прогресс: ${Math.floor(f.progress/5*100)}%<br>Выход: ⚙ ${f.output}</div>`;const a=document.createElement("button");a.className="containerAction";a.textContent="Плавить железную руду";a.onclick=()=>{if(!f.input&&f.output<64&&this.game.inventory.remove(BLOCK.IRON,1)){f.input=BLOCK.IRON;f.progress=0;this.renderFurnace(f)}};el.appendChild(a);const b=document.createElement("button");b.className="containerAction";b.textContent="Забрать слитки";b.onclick=()=>{if(f.output){this.game.inventory.add(ITEM.IRON_INGOT,f.output);f.output=0;this.renderFurnace(f)}};el.appendChild(b)}
 serialize(){return{chests:[...this.chests],furnaces:[...this.furnaces],crops:[...this.crops],xp:this.xp,level:this.level,achievements:[...this.achievements]}}
 deserialize(d){if(!d)return;this.chests=new Map(d.chests||[]);this.furnaces=new Map(d.furnaces||[]);this.crops=new Map(d.crops||[]);this.xp=d.xp||0;this.level=d.level||1;this.achievements=new Set(d.achievements||[])}
}
