import * as THREE from "https://unpkg.com/three@0.179.1/build/three.module.js";
import {Chunk} from "./Chunk.js?v=16";
import {Generator} from "./Generator.js?v=16";
import {BLOCK,INFO} from "./Block.js?v=16";

export class World{
  constructor(scene,cfg){
    this.scene=scene;this.cfg=cfg;this.chunks=new Map();this.meshes=new Map();
    this.gen=new Generator(cfg.WORLD.SEED);this.generationBusy=false;this.lastCenter="";
    this.changes=new Map();this._textureCache=new Map();
    this.materials=this.makeMaterials();this.workers=[];this.workerSeq=0;this.workerJobs=new Map();this.workerCursor=0;
    this.meshQueue=[];this.meshQueued=new Set();this.meshBuilding=false;this.initWorker();
  }
  initWorker(){try{const cores=navigator.hardwareConcurrency||2;const count=Math.max(1,Math.min(2,cores>4?2:1));for(let i=0;i<count;i++){const w=new Worker(new URL("./WorldWorker.js?v=16",import.meta.url),{type:"module"});w.onmessage=e=>{const job=this.workerJobs.get(e.data.id);if(!job)return;this.workerJobs.delete(e.data.id);if(e.data.error)job.reject(new Error(e.data.error));else job.resolve(new Uint8Array(e.data.buffer));};w.onerror=e=>{console.warn("World worker:",e.message);for(const [id,job] of this.workerJobs){job.reject(new Error("Worker failed"));this.workerJobs.delete(id)}};this.workers.push(w)}}catch(e){this.workers=[]}}
  key(x,z){return `${x},${z}`}
  makeTexture(base,accent,seed=1,mode="normal"){
    const k=`${base}|${accent}|${seed}|${mode}`;if(this._textureCache.has(k))return this._textureCache.get(k);
    const c=document.createElement("canvas");c.width=c.height=64;const g=c.getContext("2d");g.fillStyle=base;g.fillRect(0,0,64,64);let s=seed>>>0;const rnd=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};
    for(let i=0;i<220;i++){g.globalAlpha=.08+rnd()*.16;g.fillStyle=accent;g.fillRect((rnd()*64)|0,(rnd()*64)|0,1+(rnd()*3)|0,1+(rnd()*3)|0)}g.globalAlpha=1;
    if(mode==="grassTop"){g.fillStyle="#3e7e2e";for(let i=0;i<45;i++)g.fillRect((rnd()*64)|0,(rnd()*64)|0,1,2+(rnd()*4)|0)}
    if(mode==="stone"){g.fillStyle="#eee";g.globalAlpha=.18;for(let i=0;i<35;i++)g.fillRect((rnd()*64)|0,(rnd()*64)|0,1+(rnd()*2)|0,1+(rnd()*2)|0);g.globalAlpha=1}
    if(mode==="woodTop"){g.strokeStyle="#3f2818";g.lineWidth=2;for(let r=7;r<32;r+=7)g.strokeRect(32-r,32-r,r*2,r*2)}
    const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;t.colorSpace=THREE.SRGBColorSpace;this._textureCache.set(k,t);return t;
  }
  mat(a,b,s,e={},m="normal"){return new THREE.MeshLambertMaterial({map:this.makeTexture(a,b,s,m),...e})}
  makeMaterials(){const M={};const simple=(id,a,b,s,e={},mode="normal")=>{const m=this.mat(a,b,s,e,mode);M[id]=[m,m,m,m,m,m]};
    M[BLOCK.GRASS]=[this.mat("#5c9f3d","#315f2b",1),this.mat("#5c9f3d","#315f2b",2),this.mat("#70b54a","#356f2e",3,{},"grassTop"),this.mat("#79502d","#9b693d",4),this.mat("#5c9f3d","#315f2b",5),this.mat("#5c9f3d","#315f2b",6)];
    simple(BLOCK.DIRT,"#79502d","#9b693d",10);simple(BLOCK.STONE,"#777","#4f4f4f",20,{},"stone");simple(BLOCK.SAND,"#d8c17a","#a78c51",30);simple(BLOCK.GRAVEL,"#77736b","#514f4b",40);
    M[BLOCK.LOG]=[this.mat("#7d542f","#4b301d",50),this.mat("#7d542f","#4b301d",51),this.mat("#9a7043","#4d301d",52,{},"woodTop"),this.mat("#9a7043","#4d301d",53,{},"woodTop"),this.mat("#7d542f","#4b301d",54),this.mat("#7d542f","#4b301d",55)];
    simple(BLOCK.LEAVES,"#3f8e3a","#285f2b",60,{transparent:true,opacity:.92,side:THREE.DoubleSide});simple(BLOCK.PLANKS,"#a56f3f","#6d4527",90);simple(BLOCK.GLASS,"#b9e8f5","#fff",100,{transparent:true,opacity:.38,side:THREE.DoubleSide});simple(BLOCK.BRICK,"#9c4d40","#70312b",110);simple(BLOCK.WATER,"#3973c9","#20498b",120,{transparent:true,opacity:.48,side:THREE.DoubleSide});
    simple(BLOCK.COAL,"#333","#111",70);simple(BLOCK.IRON,"#a67558","#6d4633",80);simple(BLOCK.COPPER,"#9b6a52","#6d4336",240);simple(BLOCK.FURNACE,"#777","#333",135,{},"stone");simple(BLOCK.CHEST,"#9a5b28","#4e2912",150);simple(BLOCK.LANTERN,"#d79b35","#6e4217",140,{emissive:0x7a4b12,emissiveIntensity:.8});simple(BLOCK.CAMPFIRE,"#d65d24","#542012",160,{emissive:0xff4b12,emissiveIntensity:1.8});simple(BLOCK.MOSS,"#4f8744","#285b2b",170);simple(BLOCK.GLOWSTONE,"#e7c85d","#a86b19",180,{emissive:0xffaa33,emissiveIntensity:1.5});simple(BLOCK.COBBLE,"#696969","#454545",190,{},"stone");simple(BLOCK.SNOW,"#e9f2f4","#b9c6ca",200);simple(BLOCK.CLAY,"#aa7667","#704b45",210);simple(BLOCK.FARMLAND,"#6b452c","#382516",220);simple(BLOCK.WHEAT,"#7f9a39","#d2b64a",230,{transparent:true,opacity:.9,side:THREE.DoubleSide});simple(BLOCK.BEDROCK,"#171717","#292929",130);return M;}
  applyChanges(c){const s=c.size,baseX=c.cx*s,baseZ=c.cz*s;for(const [k,b] of this.changes){const [x,y,z]=k.split(",").map(Number);if(Math.floor(x/s)===c.cx&&Math.floor(z/s)===c.cz)c.set(((x%s)+s)%s,y,((z%s)+s)%s,b)}}
  async generateAround(px,pz){const s=this.cfg.WORLD.CHUNK_SIZE,r=this.cfg.WORLD.RENDER_DISTANCE,cx=Math.floor(px/s),cz=Math.floor(pz/s),center=this.key(cx,cz);if(this.generationBusy||this.lastCenter===center)return false;this.lastCenter=center;this.generationBusy=true;
    const jobs=[];for(let x=-r;x<=r;x++)for(let z=-r;z<=r;z++)if(x*x+z*z<=r*r&&!this.chunks.has(this.key(cx+x,cz+z)))jobs.push([cx+x,cz+z]);jobs.sort((a,b)=>(a[0]-cx)**2+(a[1]-cz)**2-(b[0]-cx)**2-(b[1]-cz)**2);this.generationProgress={done:0,total:jobs.length,created:0};
    try{for(const [x,z] of jobs){await this.generateChunk(x,z,true);this.generationProgress.done++;this.generationProgress.created++;await new Promise(requestAnimationFrame)}this.unloadFar(cx,cz,r+1);return true}finally{this.generationBusy=false;this.generationProgress=null}}
  generateChunk(cx,cz,useWorker=true){const s=this.cfg.WORLD.CHUNK_SIZE,h=this.cfg.WORLD.HEIGHT;if(useWorker&&this.workers.length){const id=++this.workerSeq,w=this.workers[this.workerCursor++%this.workers.length];return new Promise((resolve,reject)=>{this.workerJobs.set(id,{resolve:blocks=>{const c=new Chunk(cx,cz,s,h);c.blocks.set(blocks);this.applyChanges(c);this.chunks.set(this.key(cx,cz),c);this.queueRebuild(c);resolve(c)},reject});w.postMessage({id,seed:this.cfg.WORLD.SEED,cx,cz,size:s,height:h,seaLevel:this.cfg.WORLD.SEA_LEVEL})})}
    const c=new Chunk(cx,cz,s,h);for(let x=0;x<s;x++)for(let z=0;z<s;z++){const wx=cx*s+x,wz=cz*s+z,top=this.gen.height(wx,wz);for(let y=0;y<h;y++)c.set(x,y,z,this.gen.getWithHeight(wx,y,wz,top,this.cfg.WORLD.SEA_LEVEL));}this.applyChanges(c);this.chunks.set(this.key(cx,cz),c);this.queueRebuild(c);return c;}
  getBlock(x,y,z){if(y<0||y>=this.cfg.WORLD.HEIGHT)return BLOCK.AIR;const ck=`${x|0},${y|0},${z|0}`;if(this.changes.has(ck))return this.changes.get(ck);const s=this.cfg.WORLD.CHUNK_SIZE,cx=Math.floor(x/s),cz=Math.floor(z/s),c=this.chunks.get(this.key(cx,cz));return c?c.get(((x%s)+s)%s,y,((z%s)+s)%s):BLOCK.AIR}
  setBlock(x,y,z,b){if(y<0||y>=this.cfg.WORLD.HEIGHT)return false;const s=this.cfg.WORLD.CHUNK_SIZE,cx=Math.floor(x/s),cz=Math.floor(z/s),c=this.chunks.get(this.key(cx,cz));if(!c)return false;const lx=((x%s)+s)%s,lz=((z%s)+s)%s;c.set(lx,y,lz,b);this.changes.set(`${x|0},${y|0},${z|0}`,b);this.queueRebuild(c);if(lx===0)this.rebuildAt(cx-1,cz);if(lx===s-1)this.rebuildAt(cx+1,cz);if(lz===0)this.rebuildAt(cx,cz-1);if(lz===s-1)this.rebuildAt(cx,cz+1);return true}
  rebuildAt(cx,cz){const c=this.chunks.get(this.key(cx,cz));if(c)this.queueRebuild(c)}
  queueRebuild(c){const k=this.key(c.cx,c.cz);if(this.meshQueued.has(k))return;this.meshQueued.add(k);this.meshQueue.push(c)}
  processMeshQueue(budgetMs=3){if(this.meshBuilding||!this.meshQueue.length)return;this.meshBuilding=true;const start=performance.now();try{while(this.meshQueue.length&&performance.now()-start<budgetMs){const c=this.meshQueue.shift();this.meshQueued.delete(this.key(c.cx,c.cz));if(this.chunks.get(this.key(c.cx,c.cz))===c)this.rebuildChunk(c)}}finally{this.meshBuilding=false}}
  rebuildChunk(c){const key=this.key(c.cx,c.cz),old=this.meshes.get(key);if(old){this.scene.remove(old);old.traverse(o=>{if(o.geometry)o.geometry.dispose()})}const group=new THREE.Group(),s=c.size,bx=c.cx*s,bz=c.cz*s;
    const F=[{d:[1,0,0],n:[1,0,0],v:[[1,0,0],[1,1,0],[1,1,1],[1,0,1]]},{d:[-1,0,0],n:[-1,0,0],v:[[0,0,1],[0,1,1],[0,1,0],[0,0,0]]},{d:[0,1,0],n:[0,1,0],v:[[0,1,1],[1,1,1],[1,1,0],[0,1,0]]},{d:[0,-1,0],n:[0,-1,0],v:[[0,0,0],[1,0,0],[1,0,1],[0,0,1]]},{d:[0,0,1],n:[0,0,1],v:[[1,0,1],[1,1,1],[0,1,1],[0,0,1]]},{d:[0,0,-1],n:[0,0,-1],v:[[0,0,0],[0,1,0],[1,1,0],[1,0,0]]}];
    const groups=new Map(),solid=id=>!!INFO[id]?.solid&&!INFO[id]?.transparent;
    for(let x=0;x<s;x++)for(let y=0;y<c.height;y++)for(let z=0;z<s;z++){const id=c.get(x,y,z),info=INFO[id];if(!info||(!info.solid&&!info.liquid&&!info.emissive&&!info.plant))continue;for(let f=0;f<6;f++){const q=F[f].d,nx=x+q[0],ny=y+q[1],nz=z+q[2];let neighbor;if(nx>=0&&nx<s&&nz>=0&&nz<s&&ny>=0&&ny<c.height)neighbor=c.get(nx,ny,nz);else neighbor=this.getBlock(bx+nx,ny,bz+nz);if(!solid(neighbor)){if(!groups.has(id))groups.set(id,{p:[],n:[],u:[],i:[],groups:[]});const g=groups.get(id),start=g.i.length,base=g.p.length/3;for(const v of F[f].v){g.p.push(bx+x+v[0],y+v[1],bz+z+v[2]);g.n.push(...F[f].n)}g.u.push(0,0,0,1,1,1,1,0);g.i.push(base,base+1,base+2,base,base+2,base+3);g.groups.push({start,count:6,materialIndex:f})}}}
    for(const [id,d] of groups){const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.Float32BufferAttribute(d.p,3));g.setAttribute("normal",new THREE.Float32BufferAttribute(d.n,3));g.setAttribute("uv",new THREE.Float32BufferAttribute(d.u,2));g.setIndex(d.i);for(const q of d.groups)g.addGroup(q.start,q.count,q.materialIndex);g.computeBoundingSphere();const m=new THREE.Mesh(g,this.materials[id]||this.materials[BLOCK.STONE]);m.userData={blockId:id,chunk:c};group.add(m)}
    group.userData.chunk=c;this.scene.add(group);this.meshes.set(key,group)}
  unloadFar(cx,cz,r){for(const [k,g] of this.meshes){const [x,z]=k.split(",").map(Number);if(Math.max(Math.abs(x-cx),Math.abs(z-cz))>r){this.scene.remove(g);g.traverse(o=>{if(o.geometry)o.geometry.dispose()});this.meshes.delete(k);this.chunks.delete(k)}}}
  loadChanges(list){this.changes.clear();for(const x of list||[]){if(Array.isArray(x)&&x.length>=4)this.changes.set(`${x[0]|0},${x[1]|0},${x[2]|0}`,x[3]|0)}}
  serializeChanges(){const out=[];for(const [k,b] of this.changes){const p=k.split(",").map(Number);out.push([p[0],p[1],p[2],b])}return out}
  tickFalling(player){const r=10,px=Math.floor(player.pos.x),py=Math.floor(player.pos.y),pz=Math.floor(player.pos.z);for(let x=px-r;x<=px+r;x++)for(let z=pz-r;z<=pz+r;z++)for(let y=Math.min(this.cfg.WORLD.HEIGHT-2,py+8);y>=1;y--){const id=this.getBlock(x,y,z);if((id===BLOCK.SAND||id===BLOCK.GRAVEL)&&this.getBlock(x,y-1,z)===BLOCK.AIR){this.setBlock(x,y,z,BLOCK.AIR);this.setBlock(x,y-1,z,id)}}}
}
