import {SaveManager} from "../save/SaveManager.js";
export class Menu{
 constructor(game){this.game=game;this.main=document.getElementById("mainMenu");this.pause=document.getElementById("pauseMenu");const q=id=>document.getElementById(id);
  q("playButton").onclick=()=>this.openMode();q("settingsButton").onclick=()=>q("settingsPanel")?.classList.remove("hidden");q("creditsButton").onclick=()=>q("creditsPanel")?.classList.remove("hidden");
  q("modeBackButton").onclick=()=>this.closeAllSub();q("singleplayerChoice").onclick=()=>this.openWorlds();q("multiplayerChoice").onclick=()=>this.openMultiplayer();q("singleBackButton").onclick=()=>this.openMode();q("newWorldButton").onclick=()=>this.openCreateWorld();q("newWorldBackButton").onclick=()=>this.openWorlds();q("createWorldButton").onclick=()=>this.createWorld();
  q("closeSettings").onclick=()=>q("settingsPanel")?.classList.add("hidden");q("closeCredits").onclick=()=>q("creditsPanel")?.classList.add("hidden");q("closeMultiplayer")?.addEventListener("click",()=>this.openMode());
  const rd=q("renderDistance"),rv=q("renderValue"),sen=q("sensitivity"),sv=q("sensitivityValue"),quality=q("qualitySelect");if(rd)rd.oninput=()=>{rv.textContent=rd.value;game.world.cfg.WORLD.RENDER_DISTANCE=+rd.value;game.world.lastCenter=""};if(sen)sen.oninput=()=>{sv.textContent=sen.value;game.controls.sensitivity=+sen.value*.0003125};quality?.addEventListener("change",e=>game.setQuality(e.target.value));q("reducedMotion")?.addEventListener("change",e=>game.reducedMotion=e.target.checked);
 }
 closeAllSub(){for(const id of ["modeSelectPanel","singleplayerPanel","newWorldPanel","multiplayerPanel"])document.getElementById(id)?.classList.add("hidden");this.showMain()}
 openMode(){this.main.classList.add("hidden");for(const id of ["singleplayerPanel","newWorldPanel","multiplayerPanel"])document.getElementById(id)?.classList.add("hidden");document.getElementById("modeSelectPanel")?.classList.remove("hidden")}
 openMultiplayer(){document.getElementById("modeSelectPanel")?.classList.add("hidden");document.getElementById("multiplayerPanel")?.classList.remove("hidden")}
 openWorlds(){document.getElementById("modeSelectPanel")?.classList.add("hidden");document.getElementById("newWorldPanel")?.classList.add("hidden");document.getElementById("singleplayerPanel")?.classList.remove("hidden");this.renderWorlds()}
 openCreateWorld(){document.getElementById("singleplayerPanel")?.classList.add("hidden");document.getElementById("newWorldPanel")?.classList.remove("hidden");setTimeout(()=>document.getElementById("newWorldName")?.focus(),40)}
 createWorld(){const name=document.getElementById("newWorldName")?.value.trim()||`Новый мир ${SaveManager.listWorlds().length+1}`;const seed=document.getElementById("newWorldSeed")?.value.trim()||"";this.game.newWorld(name,seed)}
 renderWorlds(){const list=document.getElementById("worldList"),empty=document.getElementById("worldEmpty");if(!list)return;list.innerHTML="";const worlds=SaveManager.listWorlds();empty?.classList.toggle("hidden",worlds.length>0);for(const w of worlds){const item=document.createElement("div");item.className="worldItem45";const d=new Date(w.updated||w.created||Date.now());item.innerHTML='<div><div class="worldName"></div><div class="worldMeta"></div></div><div class="worldActions"><button class="worldAction45 load">ИГРАТЬ</button><button class="worldAction45 delete">✕</button></div>';item.querySelector(".worldName").textContent=w.name;item.querySelector(".worldMeta").textContent=`СИД ${w.seed} • ${d.toLocaleDateString("ru-RU")}`;item.querySelector(".load").onclick=()=>{SaveManager.setActive(w.id);sessionStorage.setItem("vs_launch_world_v50","1");location.reload()};item.querySelector(".delete").onclick=()=>{if(confirm(`Удалить мир «${w.name}»?`)){SaveManager.deleteWorld(w.id);this.renderWorlds()}};list.appendChild(item)}}
 showPause(){this.pause.classList.remove("hidden")}hidePause(){this.pause.classList.add("hidden")}showMain(){this.main.classList.remove("hidden")}hideMain(){this.main.classList.add("hidden")}
}
